# Generated by Django 3.1.14 on 2025-06-24 09:41

from django.db import migrations, models
import django.db.models.deletion
import messagebus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('value', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'TG User',
                'verbose_name_plural': 'TG Users',
                'db_table': 'common_tguser',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[messagebus.models.validate_alert_name])),
                ('title', models.CharField(max_length=200)),
                ('chat_id', models.CharField(max_length=100, validators=[messagebus.models.validate_chat_id])),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messagebus.telegrambot')),
                ('tagged_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='messagebus.tguser')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['name'], name='messagebus__name_13a8ae_idx'),
        ),
    ]
