[tool.poetry]
name = "caesar-common"
version = "0.1.0"
description = "Custom Library for common functions for Caesar (V2)"
authors = ["Asians Group LLC <dev.team@asians.cloud>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
aliyun-log-python-sdk = "==0.6.58"
autobahn = "==21.2.1"
coreapi = "~=2.3.3"
cryptography = "~=3.3.2"
daphne = "~=3.0.1"
Django = "~=3.1.7"
django-celery-results = "~=2.1.0"
django-debug-toolbar = "~=3.2"
django-elasticsearch-dsl = "==8.0"
django-filter = "~=2.4.0"
django-rest-auth = "~=0.9.5"
django-slack = "~=5.16.0"
djangorestframework = "~=3.12.2"
djangorestframework-jwt = "~=1.11.0"
elasticsearch-dsl = "==8.14.0"
jwt = "~=1.2.0"
psycopg2-binary = "~=2.8.6"
pyasn1 = "~=0.4.8"
python = "^3.9.0"
python-dotenv = "~=0.15.0"
python-telegram-bot = "~=13.14"
pytz = "~=2021.1"
requests = ">=2.25.1"
six = "~=1.15.0"
Twisted = "~=21.2.0"
uWSGI = ">=2.0.19"
utils2devops = ">=0.1.4"

[tool.poetry.group.git.dependencies]
caesar-user = { git = "https://github.com/rq0net/caesar-user", rev = "8bbbe47" }
django-keycloak = { git = "https://github.com/rq0net/django-keycloak", rev = "e6fb90024a9a8b5a2546fef40443572c968b9e8e" }
django-jsoneditor = { git = "https://github.com/martn/django-jsoneditor", rev = "108bc86b134bc926fa584064a132b5be1640cb5c" }
django-ajax-selects = { git = "https://github.com/rq0net/django-ajax-selects", rev = "1c4c7f8" }

[tool.poetry.group.dev.dependencies]
jupyterlab = "*"
pylint = "*"

[tool.poetry.group.test.dependencies]
atomicwrites = ">=1.3.0"
attrs = ">=19.1.0"
coverage = ">=4.5.3"
more-itertools = ">=7.0.0"
pluggy = ">=0.12.0"
py = "==1.8.0"
pycodestyle = "*"
pygments = ">=2.4.2"
pytest = ">=4.6.3"
pytest-cov = "*"
pytest-django = ">=3.4.8"
pytest-pep8 = ">=1.0.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
