# Generated by Django 3.1.7 on 2021-02-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30)),
                ('realm', models.CharField(max_length=30)),
                ('user_domain', models.CharField(max_length=30)),
                ('cluster', models.CharField(max_length=30)),
            ],
        ),
    ]
