from enum import Enum

class AlertName(Enum):
    # caesar cert
    CERT_ISSUE_SUCCESS = 'CERT_ISSUE_SUCCESS'
    CERT_ISSUE_FAILURE = 'CERT_ISSUE_FAILURE'
    CERT_PRE_CHECK = 'CERT_PRE_CHECK'
    CERT_RENEW_START = 'CERT_RENEW_START'
    CERT_RENEW_END = 'CERT_RENEW_END'
    CERT_RENEW_FAILURE = 'CERT_RENEW_FAILURE'
    CERT_EXPIRY_WARNING = 'CERT_EXPIRY_WARNING'
    CERT_CLEANUP = 'CERT_CLEANUP'
    # caesar cdndomain
    USER_NEW = 'USER_NEW'
    DEPLOY_SUCCESS = 'DEPLOY_SUCCESS'
    DEPLOY_FAILURE_DEFAULT = 'DEPLOY_FAILURE_DEFAULT'
    DEPLOY_FAILURE_NOHOST = 'DEPLOY_FAILURE_NOHOST'
    DEPLOY_FAILURE_NODOMAIN = 'DEPLOY_FAILURE_NODOMAIN'
    DEPLOY_EXCEPTION = 'DEPLOY_EXCEPTION'
    DEPLOY_DOMAIN_NEW = 'DEPLOY_DOMAIN_NEW'
    DEPLOY_DOMAIN_DELETED = 'DEPLOY_DOMAIN_DELETED'
    DOMAIN_UPSTREAM_INVALID = 'DOMAIN_UPSTREAM_INVALID'
    DOMAIN_UPSTREAM_RECOVERY = 'DOMAIN_UPSTREAM_RECOVERY'
    CLEAR_CACHE_SUCCESS = 'CLEAR_CACHE_SUCCESS'
    CLEAR_CACHE_FAILURE = 'CLEAR_CACHE_FAILURE'
    TRAFFIC_OVERRUN = 'TRAFFIC_OVERRUN'
    TRAFFIC_OVERLIMIT = 'TRAFFIC_OVERLIMIT'
    TRAFFIC_DAILY_TOP_DOMAIN = 'TRAFFIC_DAILY_TOP_DOMAIN'
    TRAFFIC_MONTHLY_TOP_DOMAIN = 'TRAFFIC_MONTHLY_TOP_DOMAIN'
    TRAFFIC_WEEKLY_TOP_FREE = 'TRAFFIC_WEEKLY_TOP_FREE'
    # ES WebHook
    ES_ALERT_FAKEWALL3 = 'ES_ALERT_FAKEWALL3'
    ES_ALERT_FAKEWALL2 = 'ES_ALERT_FAKEWALL2'
    ES_ALERT_425 = 'ES_ALERT_425'
    ES_ALERT_L7_ATTACK = 'ES_ALERT_L7_ATTACK'
    ES_UPSTREAM_TIMEOUT = 'ES_UPSTREAM_TIMEOUT'
    ES_IP_PERCENTAGE = 'ES_IP_PERCENTAGE'
    ES_ALERT_DEFAULT = 'ES_ALERT_DEFAULT'

ALERT_NAME_CHOICES = [(name.value, name.value) for name in AlertName]