
.. _`Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice
.. _`caesar-common`: https://github.com/rq0net/caesar-common
.. _`Issue Cookiescutter-drf-microservice`: https://github.com/alainivars/cookiecutter-drf-microservice/issues
.. _`Issue Drf-microservice`: https://github.com/alainivars/drf-microservice/issues
.. _`Issue caesar-common`: https://github.com/rq0net/caesar-common/issues
.. _`Readthedoc`: https://caesar-common.readthedocs.io/en/latest/
.. _`Github`: https://github.com/rq0net/caesar-common
.. _`Releases notes`: https://github.com/rq0net/caesar-common/blob/master/docs/releases_notes.rst
