kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "django.fullname" . }}-sites-enabled-configmap
data:
  ucr-app.conf: |
    upstream django-daphne {
      server 127.0.0.1:9000 fail_timeout=0;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
      listen 0.0.0.0:{{ .Values.nginx.listenPort }};
      client_max_body_size 4G;

      # set the correct host(s) for your site
      server_name {{ join " " .Values.nginx.hosts }};

      access_log /var/log/nginx/access.log combined;
      error_log  /var/log/nginx/error.log info;

      keepalive_timeout 5;

      # path for static files (only needed for serving local staticfiles)
      root /var/www/html/;

      location @process_uwsgi {
        proxy_pass  http://django-daphne;
        proxy_read_timeout 300s;
      }
      
      #path to proxy my WebSocket requests
      location /ws/ {
         proxy_pass  http://django-daphne;
         
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
         proxy_buffering off;
         proxy_redirect off;
         proxy_connect_timeout 60s;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Host $server_name;
      }

      location / {
        try_files $uri $uri/ @process_uwsgi;
      }

      # location / {
      #   # checks for static file, if not found proxy to app
      #   try_files $uri @proxy_to_app;
      # }

      # location @proxy_to_app {
      #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #   proxy_set_header X-Forwarded-Proto $scheme;
      #   proxy_set_header Host $http_host;

      #   proxy_redirect off;
      #   proxy_pass http://app_server;
      # }

      error_page 500 502 503 504 /500.html;
      location = /500.html {
        root /var/www/html/;
      }
    }
